Organizations:
  - &OrdererOrg
    Name: OrdererOrgMSP
    ID: OrdererOrgMSP
    MSPDir: ../crypto-config/ordererOrganizations/main.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.admin')"

  - &MainOrg
    Name: MainOrgMSP
    ID: MainOrgMSP
    MSPDir: ../crypto-config/peerOrganizations/main.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MainOrgMSP.admin', 'MainOrgMSP.peer', 'MainOrgMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('MainOrgMSP.admin', 'MainOrgMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MainOrgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MainOrgMSP.peer')"
    AnchorPeers:
      - Host: peer0.main.com
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer0.main.com:7050
    - orderer1.main.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 10MB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  EtcdRaft:
    Consenters:
      - Host: orderer0.main.com
        Port: 7050
        ClientTLSCert: ../crypto-config/ordererOrganizations/main.com/orderers/orderer0.main.com/tls/server.crt
        ServerTLSCert: ../crypto-config/ordererOrganizations/main.com/orderers/orderer0.main.com/tls/server.crt
      - Host: orderer1.main.com
        Port: 7050
        ClientTLSCert: ../crypto-config/ordererOrganizations/main.com/orderers/orderer1.main.com/tls/server.crt
        ServerTLSCert: ../crypto-config/ordererOrganizations/main.com/orderers/orderer1.main.com/tls/server.crt

Profiles:
  OrdererGenesis:
    Capabilities:
      <<: *ChannelCapabilities
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
      BlockValidation:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Orderer:
      <<: *OrdererDefaults
      Capabilities:
        <<: *OrdererCapabilities
      Organizations:
        - *OrdererOrg
    Consortiums:
      MainConsortium:
        Organizations:
          - *MainOrg

  MainChannel:
    Capabilities:
      <<: *ChannelCapabilities
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
    Consortium: MainConsortium
    Application:
      Capabilities:
        <<: *ApplicationCapabilities
      Organizations:
        - *MainOrg